set relativenumber
set nowrap
syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set runtimepath^=~/.vim/bundle/ctrlp.vim
set visualbell
set guioptions-=RrlL
colorscheme deep-space
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap j gj
nnoremap k gk
imap jj <Esc>
nnoremap <C-n> gt
nnoremap <C-m> gT

set splitbelow
set splitright
