" Pug installed
filetype off
let __filepath = expand("~/.pug/source/vim/pug")
execute 'source '.fnameescape(__filepath)
" Line numbers and relative numbers
set relativenumber
set number

" Leader as space key
let mapleader=" "

" Allow backspace in more locations
set backspace=indent,eol,start

" Disable line wrap
set nowrap

" Change syntax based on file types
syntax on
filetype plugin indent on 
colorscheme lemon-orchard

" 2 space indent is life
set tabstop=2
set shiftwidth=2
set expandtab

" Split character the same as tmux

set fillchars+=vert:│

" Enable ctrl-p
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
" Shortcuts for common operations
let g:ctrlp_map = '<leader>f'

" nREPL support
" Requires CIDER-nREPL to be installed in lein
" Add this to the user profile: [cider/cider-nrepl "0.14.0"]
nnoremap <leader>e :Eval<CR>
nnoremap <leader>E :%Eval<CR>

noremap <leader>p :set paste!<CR>

" Allow for buffers in the background
set hidden

" jk as escape in insert mode
imap jk <Esc>
vmap jk <Esc>
imap jj na-aa

" C-n, C-p to switch tabs
nnoremap <silent> <C-n> :bn<CR>
nnoremap <silent> <C-p> :bp<CR>
nnoremap <silent> <C-x> :bd<CR>:bn<CR>
nnoremap Y y$

" Open new splits in the 'other' location
set splitbelow
set splitright

" Highlight line for keeping under 80 chars
set colorcolumn=81

" Some other stuff
set visualbell

" Show a menu for command completions
set wildmenu

" Don't redraw as much
set lazyredraw

" Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_auto_jump = 0
let g:syntastic_enable_signs = 0

" Crazy hacks for alt key to work as shortcut
let c='a'
while c <= 'z'
  exec "set <A-".c.">=\e".c
  exec "imap \e".c." <A-".c.">"
  let c = nr2char(1+char2nr(c))
endw

set timeout ttimeoutlen=50

" Load config for this device
let __filepath = expand("~/.vimrc-local")
if filereadable(__filepath)
  execute 'source '.fnameescape(__filepath)
endif

