#!/bin/zsh

source ~/.shell/autoload.sh

# Prompt
autoload -U colors
colors
setopt prompt_subst
PROMPT='%(?.%F{$HOST_COLOR}.%F{red})>%f '

# History
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HISTIGNORESPACE
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/._zsh_history
setopt inc_append_history share_history

REPORTTIME=10

# Vim key bindings

bindkey -v
export KEYTIMEOUT=50

bindkey -M viins 'jk' vi-cmd-mode
# Allow deleting into non-inserted text
bindkey "^?" backward-delete-char

function zle-line-init zle-keymap-select {
  VIM_PROMPT="%F{252}%F{0}%K{252} NORMAL %f%k"
  RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}"
  zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

# This autoload is required on macOS for completion (For some reason)
autoload -U compinit && compinit
source ~/.zsh/tmux_complete.zsh


export HIGHLIGHTING_ENABLED=true
# Load config specific to this device
__local_file="$HOME/.zshrc-local" 
if [ -e $__local_file ]; then
  source $__local_file
fi

source ~/.shell/welcome.sh

# Pug installed
source "$HOME/.pug/source/zsh/pug"

if [ -z "$TMUX" ]; then
  case $- in
    *i*) tmux attach ;;
  esac
fi
