#!/bin/zsh

funcpath="$HOME/.shell/autoload"
FPATH="$funcpath:$FPATH"
autoload ${=$(cd "$funcpath" && echo *)}
unset funcpath

source ~/.shell/alias.sh
source ~/.zsh/completions.zsh

# ALIASES
for mode in +x -x +r -r +w -r 777 755; do
  eval "$mode() { chmod $mode \"\$@\" }"
done
alias -g CL=" | wc -l"
alias -g CC=" | wc -c"
alias -g LESS=" | less"

alias -g '::'=" | less"
alias -g '??'=" | grep -E"
alias -g ':?'=" | grep -vE"

local short='...'
local long='../..'
for dots in {1..10}; do
  alias -g $short=$long
  short="${short}."
  long="$long/.."
done
# Prompt
setopt prompt_subst
PROMPT='%(?.%F{$HOST_COLOR}.%F{red})||>%f '

# History
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HISTIGNORESPACE
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/._zsh_history
setopt inc_append_history share_history

REPORTTIME=10

# Pug installed
source "$HOME/.pug/source/zsh/pug"

export FZF_TMUX_OPTS="-p"
export FZF_CTRL_R_OPTS="--reverse --preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"

if [ -d /opt/homebrew/Cellar/fzf/*/shell/ ]; then
  source /opt/homebrew/Cellar/fzf/*/shell/key-bindings.zsh
fi

hostname_color

if [ -z "$TMUX" ] && [ -n "$SSH_CLIENT" ]; then
  case $- in
    *i*) print_welcome; tmux attach || mx tmux ;;
  esac
fi

if which z > /dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi