#!/bin/bash

for file in ~/.shell/*.sh; do
  if ! [[ "$(basename "$file")" = _* ]]; then
    source "$file"
  fi
done

# Prompt
function __prompt() {
  local status=$?
  local color=$HOST_COLOR
  local face="^_^"
  if [ $status -ne 0 ]; then
    color=9
    face="x_x"
  fi
  PS1="\\033[38;5;${color}m$face \[\033[0;37m\](\W) "
}
export PROMPT_COMMAND=__prompt

# Load config specific to this device
__local_file="$HOME/.bash_profile-local" 
if [ -e $__local_file ]; then
  source $__local_file
fi

source ~/.shell/_welcome.sh
