#!/bin/bash

source ~/.shell/autoload.sh

# Prompt
function __prompt() {
  local status=$?
  local color=$hostname_color
  local face="^_^"
  if [ $status -ne 0 ]; then
    color=9
    face="x_x"
  fi
  PS1="\\033[38;5;${color}m$face \[\033[0;37m\](\W) "
}
export PROMPT_COMMAND=__prompt

# Load config specific to this device
__local_file="$HOME/.bash_profile-local" 
if [ -e $__local_file ]; then
  source $__local_file
fi

source ~/.shell/welcome.sh
